server:
  port: 8080
spring:
  application:
    name: "MonitoringSystem"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  messaging:
    provider: ${MESSAGING_PROVIDER}
  kinesis:
    region: ${AWS_REGION}
    endpoint-override: ${AWS_KINESIS_ENDPOINT_OVERRIDE}
    access-key-id: ${AWS_KINESIS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_KINESIS_SECRET_ACCESS_KEY}
    stream:
      main: ${AWS_KINESIS_STREAM_MAIN}
      dlt: ${AWS_KINESIS_STREAM_DLT}
    consumer:
      shard-iterator-type: ${AWS_KINESIS_SHARD_ITERATOR_TYPE}
      poll-interval-ms: ${AWS_KINESIS_POLL_INTERVAL_MS}
      max-records: ${AWS_KINESIS_MAX_RECORDS}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      main: ${KAFKA_TOPIC_MAIN}
      dlt: ${KAFKA_TOPIC_DLT}
    producer:
      acks: ${KAFKA_PRODUCER_ACKS}
      retries: ${KAFKA_PRODUCER_RETRIES}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${KAFKA_CONSUMER_OFFSET_RESET}
      concurrency: ${KAFKA_LISTENER_CONCURRENCY}
